Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-03, with the labels that each got.

#72 Fixing pr comment for ocp stable version
  renovate.json
Labels: approved, lgtm

#73 fine-tuning renovate config file and versions file to match latest releases
  renovate.json
  versions.yaml
Labels: approved, lgtm

#59 Update top-of-tree GPU Operator OLM bundle image path
  README.md
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
  renovate.json
  tests/nvidiagpu/deploy-gpu-test.go
Labels: approved, lgtm

#76 Test only a subset of OpenShift versions when a new digest of the image bundle for NVIDIA's GPU Operator is live
  renovate.json
Labels: approved, lgtm

#80 Nfd refactoring
  go.mod
  pkg/global/const.go
  pkg/nfd/config.go
  pkg/nfd/consts.go
  pkg/nfd/deploy-nfd.go
  pkg/nfd/nodefeaturediscovery.go
  pkg/nfd/utils.go
  pkg/nfdcheck/checknfd.go
  pkg/nvidiagpu/consts.go
  pkg/nvidiagpu/gpuBurnConfig.go
  tests/nvidiagpu/deploy-gpu-test.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: lgtm, needs-ok-to-test

#83 Adding gitignore for generated files
  .github/workflows/update-versions.yaml
  .gitignore
Labels: approved, lgtm

#84 Improve version update workflow
  .github/workflows/update-versions.yaml
  workflows/README.md
  workflows/nvidia_gpu_operator.py
  workflows/openshift.py
  workflows/settings.py
  workflows/update_versions.py
  workflows/update_versions_test.py
  workflows/utils.py
  workflows/versions.json
Labels: approved, lgtm

#86 Test the OLM bundle only with latest OpenShift
  workflows/README.md
  workflows/nvidia_gpu_operator.py
  workflows/openshift.py
  workflows/update_versions.py
  workflows/update_versions_test.py
  workflows/utils.py
  workflows/utils_test.py
Labels: approved, lgtm

#87 Delete Renovate config
  renovate.json
  versions.yaml
Labels: approved, lgtm

#89 Improve logging
  workflows/nvidia_gpu_operator.py
  workflows/openshift.py
  workflows/utils.py
Labels: approved, lgtm

#97 making a logger func
  workflows/nvidia_gpu_operator.py
  workflows/openshift.py
  workflows/utils.py
Labels: approved, lgtm

#100 Make version update flow conditional
  .github/workflows/update-versions.yaml
Labels: approved, lgtm

#98 Updates to support deploying Nvidia Network Operator (NNO) OLM bundle
  internal/deploy/deploy.go
  internal/deploy/deploy_test.go
  internal/deploy/mock_appsv1.go
  internal/deploy/mock_corev1.go
  internal/deploy/mock_deploy.go
  internal/deploy/suite_test.go
  pkg/nvidiagpu/consts.go
  tests/nvidiagpu/deploy-gpu-test.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved, lgtm

#104 Replace OCP release API
  .github/workflows/update-versions.yaml
  .gitignore
  workflows/README.md
  workflows/nvidia_gpu_operator.py
  workflows/openshift.py
  workflows/openshift_test.py
  workflows/requirements.txt
  workflows/settings.py
  workflows/utils.py
Labels: approved, lgtm

#111 Test GPU operator bundle with earliest supported OpenShift
  .github/workflows/update-versions.yaml
  workflows/update_versions_test.py
  workflows/utils.py
  workflows/utils_test.py
Labels: approved, lgtm

#109 updates to support creating NNO macvlannetwork CR
  internal/wait/networkwait.go
  pkg/nvidianetwork/macvlannetwork.go
  pkg/nvidianetwork/nicclusterpolicy.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved, lgtm

#112 Fix logging and comments
  internal/wait/networkwait.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved, lgtm

#116 adding intenal lib for rdma testing
  internal/rdma/rdma-test.go
Labels: approved, lgtm

#121 Added support for end-to-end RDMA testcase for NNO
  README.md
  internal/nvidianetworkconfig/config.go
  internal/rdma/rdma-test.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved

#113 Create a test matrix for pre-submit CI jobs(#210)
  .github/workflows/generate_matrix_page.yaml
  .gitignore
  workflows/test_matrix_dashboard/README.md
  workflows/test_matrix_dashboard/generate_test_matrix_data.py
  workflows/test_matrix_dashboard/generate_test_matrix_ui.py
  workflows/test_matrix_dashboard/logger.py
  workflows/test_matrix_dashboard/requirements.txt
Labels: approved, lgtm, ok-to-test

#125 Add AdamKaabyia to OWNERS
  OWNERS
Labels: approved, lgtm

#123 Preserve all GH pages files, including created manually
  .github/workflows/generate_matrix_page.yaml
Labels: approved, lgtm

#120 Bump github.com/regclient/regclient from 0.7.0 to 0.7.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#126 Updated matrix dashboard
  .github/workflows/generate_matrix_page.yaml
  workflows/test_matrix_dashboard/README.md
  workflows/test_matrix_dashboard/generate_test_matrix_ui.py
  workflows/test_matrix_dashboard/templates/footer.html
  workflows/test_matrix_dashboard/templates/header.html
  workflows/test_matrix_dashboard/templates/main_table.html
Labels: approved, lgtm

#127 Minor improvement to test report HTML
  workflows/test_matrix_dashboard/generate_test_matrix_ui.py
  workflows/test_matrix_dashboard/templates/footer.html
  workflows/test_matrix_dashboard/templates/main_table.html
Labels: approved, lgtm
