Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-06, with the labels that each got.

#148 adding method for deleting mofed driver
  internal/rdma/rdma-test.go
Labels: approved, lgtm

#198 Allow notes per OpenShift version
  .github/workflows/generate_matrix_page.yaml
  workflows/fetch_ci_data.py
  workflows/generate_ci_dashboard.py
  workflows/templates/main_table.html
Labels: approved, lgtm

#197 Enable notes per OpenShift version, add a note for 4.12
  gpu_operator_matrix.json
  gpu_operator_matrix_old.json
  styles.css
Labels: lgtm

#199 Add TOC to the generated dashboard
  workflows/generate_ci_dashboard.py
  workflows/templates/main_table.html
Labels: approved, lgtm

#220 Fix internal pkg rdma
  internal/rdma/rdma-test.go
Labels: approved
