Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-01, with the labels that each got.

#51 increased waiting time for ClusterPolicy, from 12minutes to 20minutes
  README.md
  tests/nvidiagpu/deploy-gpu-test.go
Labels: approved, lgtm, needs-ok-to-test

#52 Adding TomerNewman to OWNERS file
  OWNERS
Labels: approved, lgtm

#48 Using nvidia's must-gather.sh
  Containerfile
  Makefile
  internal/config/config.go
  internal/wait/wait.go
  pkg/olm/catalogsource.go
  scripts/test-runner.sh
  tests/dummy/dummy_suite_test.go
  tests/nvidiagpu/gpu_suite_test.go
Labels: approved, lgtm

#54 Making Must gather function a generic one
  internal/reporter/reporter.go
  tests/nvidiagpu/gpu_suite_test.go
Labels: approved, lgtm

#49 Add white list
  pkg/nfd/nodefeaturediscovery.go
  pkg/nfd/nodefeaturediscoveryconfig.go
Labels: approved
