Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-08, with the labels that each got.

#266 changing version that the CI has passed for them
  workflows/versions.json
Labels: approved

#271 Updating to latest gpu bundle
  workflows/versions.json
Labels: approved, ok-to-test

#273 update gpu bundle version
  workflows/versions.json
Labels: approved, ok-to-test

#275 update latest bundle versions
  workflows/versions.json
Labels: approved, ok-to-test

#280 Updating the html dashboard after running the workflow with "ALL" prs
  gpu_operator_matrix.html
  gpu_operator_matrix.json
Labels: lgtm

#278 Updating 4.19.9 and latest bundle
  workflows/versions.json
Labels: approved, lgtm, ok-to-test

#286 removing last line in versions.json
  workflows/versions.json
Labels: approved, lgtm

#291 Separate workflows into sub-directories
  .github/workflows/generate_matrix_page.yaml
  .github/workflows/generate_microshift_dashboard.yaml
  .github/workflows/update-versions.yaml
  workflows/README.md
  workflows/README_ci.md
  workflows/common/__init__.py
  workflows/common/templates.py
  workflows/common/utils.py
  workflows/gpu_operator_dashboard/README.md
  workflows/gpu_operator_dashboard/__init__.py
  workflows/gpu_operator_dashboard/fetch_ci_data.py
  workflows/gpu_operator_dashboard/generate_ci_dashboard.py
  workflows/gpu_operator_dashboard/requirements.txt
  workflows/gpu_operator_dashboard/templates/footer.html
  workflows/gpu_operator_dashboard/templates/header.html
  workflows/gpu_operator_dashboard/templates/main_table.html
  workflows/gpu_operator_dashboard/tests/test_generate_data.py
  workflows/gpu_operator_dashboard/tests/test_generate_ui.py
  workflows/gpu_operator_versions/README.md
  workflows/gpu_operator_versions/__init__.py
  workflows/gpu_operator_versions/nvidia_gpu_operator.py
  workflows/gpu_operator_versions/openshift.py
  workflows/gpu_operator_versions/requirements.txt
  workflows/gpu_operator_versions/settings.py
  workflows/gpu_operator_versions/tests/test_openshift.py
  workflows/gpu_operator_versions/tests/test_update_versions.py
  workflows/gpu_operator_versions/tests/test_version_utils.py
  workflows/gpu_operator_versions/update_versions.py
  workflows/gpu_operator_versions/version_utils.py
  workflows/gpu_operator_versions/versions.json
  workflows/microshift_dashboard/README.md
  workflows/microshift_dashboard/__init__.py
  workflows/microshift_dashboard/microshift.py
  workflows/microshift_dashboard/requirements.txt
  workflows/microshift_dashboard/templates/microshift.html
  workflows/update_versions.py
Labels: approved, lgtm
