Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-09, with the labels that each got.

#296 Update GPU operator test results following change in logic
  gpu_operator_matrix.html
  gpu_operator_matrix.json
  styles.css
Labels: lgtm

#311 Running dashboard generation on closed PRs
  .github/workflows/generate_matrix_page.yaml
Labels: approved, lgtm

#316 Revert NVIDIA GPU Operator to 25.3.3 as 25.3.4 isn't published yet
  workflows/gpu_operator_versions/versions.json
Labels: approved
