Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-04, with the labels that each got.

#130 Use custom access token for GH pages
  .github/workflows/generate_matrix_page.yaml
Labels: approved, lgtm

#131 Try to fix workflow permission for gh-pages
  .github/workflows/generate_matrix_page.yaml
Labels: approved, lgtm

#134 dashboard bug fixes
  .github/workflows/generate_matrix_page.yaml
  workflows/README_ci.md
  workflows/dashboard_requirements.txt
  workflows/generate_ci_dashboard.py
  workflows/templates/footer.html
  workflows/templates/header.html
  workflows/templates/main_table.html
  workflows/test_matrix_dashboard/README.md
  workflows/test_matrix_dashboard/generate_test_matrix_data.py
  workflows/test_matrix_dashboard/generate_test_matrix_ui.py
  workflows/test_matrix_dashboard/logger.py
  workflows/test_matrix_dashboard/requirements.txt
  workflows/tests/test_generate_data.py
  workflows/tests/test_generate_ui.py
  workflows/utils.py
Labels: approved, lgtm

#137 Rename JSON files to match new scheme
  gpu_operator_matrix.json
  gpu_operator_matrix_old.json
Labels: lgtm

#142 Remove CSS from the templates, use an external file
  workflows/templates/footer.html
  workflows/templates/header.html
  workflows/templates/main_table.html
Labels: approved, lgtm

#149 Updates to pass parameters in env vars and few fixes
  README.md
  internal/nvidianetworkconfig/config.go
  internal/rdma/rdma-test.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved

#154 Added support to create IPoIBNetwork Custom CR and infiniband RDMA
  README.md
  internal/nvidianetworkconfig/config.go
  internal/wait/networkwait.go
  pkg/nvidianetwork/ipoibnetwork.go
  tests/nvidianetwork/deploy-nno-test.go
Labels: approved

#157 Enable GPU operator jobs on OCP 4.13
  .github/workflows/update-versions.yaml
Labels: approved, lgtm

#156 Running the must gather script after successful run
  internal/config/config.go
  internal/reporter/reporter.go
  tests/nvidiagpu/gpu_suite_test.go
Labels: approved, lgtm

#159 Add 4.13 manually from test rehearsals
  gpu_operator_matrix.json
Labels: lgtm
