Repository rh-ecosystem-edge/nvidia-ci, pull requests merged in 2025-07, with the labels that each got.

#228 getting NFD alm example instead of first one
  pkg/nfd/nodefeaturediscovery.go
  pkg/olm/almexamples.go
Labels: approved, lgtm

#236 USHIFT-5771: Skip MicroShift dashboard generation if no updates
  .github/workflows/generate_microshift_dashboard.yaml
Labels: approved, lgtm, ok-to-test

#237 Regenerate GPU Operator Matrix
  gpu_operator_matrix.html
Labels: needs-ok-to-test

#245 Remove 4.20 that was added by mistake
  gpu_operator_matrix.json
Labels: lgtm

#226 Adding NFD must gather script
  Makefile
  internal/reporter/reporter.go
  scripts/gpu-operator-tests-must-gather.sh
  scripts/test-runner.sh
  tests/nvidiagpu/gpu_suite_test.go
Labels: approved, lgtm

#250 Add vtruhpon to OWNERS file
  OWNERS
Labels: approved, lgtm
